name: Docker Build
on:
  workflow_dispatch:
jobs:
  server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./server
          target: production
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tasks-app-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tasks-app-server:${{ github.sha }}
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ./client
          target: production
          push: true
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tasks-app-client:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tasks-app-client:${{ github.sha }}
